(require 'newsticker)
(require 'w3m)

(setq newsticker-html-renderer 'w3m-region)
(setq newsticker-retrieval-interval 1800)
(setq newsticker-retrieval-method 'extern)

(setq newsticker-automatically-mark-items-as-old nil)
(setq newsticker-keep-obsolete-items t)

(setq newsticker-url-list-defaults nil)

(setq newsticker-url-list
      '(("AmazingSuperPowers" "http://www.amazingsuperpowers.com/category/comics/feed/" nil nil nil)
        ("Andrzej Rysuje | Rysunki Satyryczne" "http://www.andrzejrysuje.pl/feed/" nil nil nil)
        ("boli blog" "http://boli.blog.pl/index.rss" nil nil nil)
        ("Buttersafe - Updated Tuesdays and Thursdays" "http://buttersafe.com/feed/" nil nil nil)
        ("Channelate" "http://www.channelate.com/feed/" nil nil nil)
        ("Completely Serious Comics" "http://www.completelyseriouscomics.com/?feed=rss2" nil nil nil)
        ("Dresden Codak" "http://feeds.feedburner.com/rsspect/fJur" nil nil nil)
        ("Dwarf Fortress Development Log" "http://www.bay12games.com/dwarves/dev_now.rss" nil nil nil)
        ("Emacs Redux" "http://emacsredux.com/atom.xml" nil nil nil)
        ("emacs-fu" "http://emacs-fu.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
        ("Explosm.net" "http://feeds.feedburner.com/Explosm" nil nil nil)
        ("Gergő.Érdi.hu" "http://gergo.erdi.hu/blog/tags/all/feed.xml" nil 3600 nil)
        ("GitHub" "https://github.com/Idorobots.private.atom?token=bf84188302178d642d8ee06eee7aa582" nil nil nil)
        ("Gun Show ~ ~ ~ ~" "http://www.rsspect.com/rss/gunshowcomic.xml" nil nil nil)
        ("Hejibits" "http://www.hejibits.com/feed/" nil nil nil)
        ("Lambda the Ultimate - Programming Languages Weblog" "http://lambda-the-ultimate.org/rss.xml" nil 1200 nil)
        ("language agnostic" "http://langnostic.blogspot.com/feeds/posts/default?alt=rss" nil nil nil)
        ("League Of Super Redundant Heroes" "http://superredundant.com/?feed=rss2" nil nil nil)
        ("Lispjobs" "http://lispjobs.wordpress.com/feed/" nil 1200 nil)
        ("Mozilla Memes" "http://mozillamemes.tumblr.com/rss" nil 1200 nil)
        ("New Subscription Videos" "http://gdata.youtube.com/feeds/base/users/VA15LHg4AmQKAPFaoOPjXg/newsubscriptionvideos?client=ytapi-youtube-user&v=2" nil 1200 nil)
        ("Oglaf! -- Comics. Often dirty." "http://www.oglaf.com/feeds/rss/" nil nil nil)
        ("Order of the Stick" "http://www.giantitp.com/comics/oots.rss" nil nil nil)
        ("Parallella" "http://www.parallella.org/feed/" nil nil nil)
        ("Saturday Morning Breakfast Cereal (updated daily)" "http://www.smbc-comics.com/rss.php" nil 1200 nil)
        ("Scandinavia and the World" "http://feeds.feedburner.com/satwcomic" nil 3600 nil)
        ("The Perry Bible Fellowship" "http://pbfcomics.com/feed/feed.xml" nil nil nil)
        ("Two Guys and Guy" "http://feeds.feedburner.com/TwoGuysAndGuy" nil nil nil)
        ("Wolfire Games Blog" "http://feeds.wolfire.com/WolfireGames" nil 3600 nil)
        ("xkcd.com" "http://xkcd.com/atom.xml" nil 1200 nil)
        ("Zero Punctuation" "http://www.escapistmagazine.com/rss/videos/list/1.xml" nil nil nil)))

(global-set-key (kbd "C-c r") 'newsticker-treeview)
;(newsticker-start)

(provide 'my-rss-reader)